//! The container, against real HEIC files encoded by macOS.
//!
//! Every value asserted here was read out of the files themselves with a
//! separate box walker before being written down, so these are exact
//! expectations rather than whatever the crate happens to produce.
//!
//! The fixtures are generated by `scripts/make-fixtures.sh` from PNGs this
//! project synthesises; see `tests/fixtures/README.md`.

use heic_rs::context::Context;
use heic_rs::ftyp::Brand;
use heic_rs::hevc::ChromaFormat;
use heic_rs::props::simple::Rotation;

fn load(name: &str) -> Vec<u8> {
    let path = format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read(&path).unwrap_or_else(|e| panic!("fixture {path} is missing: {e}"))
}

const ALL: [&str; 9] = [
    "flat-white-16.heic",
    "flat-64.heic",
    "checker-64.heic",
    "rgb-strips-96.heic",
    "gradient-512.heic",
    "checker-1024.heic",
    "photo-2048.heic",
    "rotated-90.heic",
    "with-exif.heic",
];

#[test]
fn every_fixture_probes_without_decoding() {
    for name in ALL {
        let info = heic_rs::probe(&load(name)).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(info.brand, Brand::Heic, "{name}");
        assert_eq!(info.bit_depth, 8, "{name}");
        assert_eq!(info.chroma, ChromaFormat::Yuv420, "{name}");
        // Every one of these files carries an `irot` of zero degrees, so
        // "irot is present" must not be read as "the image is rotated".
        assert_eq!(info.rotation, Rotation::None, "{name}");
        assert_eq!(info.mirror, None, "{name}");
        assert!(!info.has_alpha, "{name}");
        assert!(!info.has_icc, "{name}");
        assert_eq!(info.width, info.coded_width, "{name}");
        assert_eq!(info.height, info.coded_height, "{name}");
    }
}

#[test]
fn single_item_fixtures_have_the_sizes_they_were_made_at() {
    for (name, w, h) in [
        ("flat-white-16.heic", 16, 16),
        ("flat-64.heic", 64, 64),
        ("checker-64.heic", 64, 64),
        ("rgb-strips-96.heic", 96, 32),
        ("gradient-512.heic", 512, 512),
    ] {
        let info = heic_rs::probe(&load(name)).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!((info.width, info.height), (w, h), "{name}");
        assert_eq!(info.primary_item, 1, "{name}");
        assert!(!info.is_grid, "{name} should be a single coded item");
        assert!(info.grid.is_none(), "{name}");
        assert!(!info.has_exif, "{name}");
    }
}

#[test]
fn grid_fixtures_report_their_exact_tiling() {
    for (name, primary, rows, cols, w, h) in [
        ("checker-1024.heic", 5, 2, 2, 1024, 1024),
        ("photo-2048.heic", 13, 3, 4, 2048, 1536),
        ("rotated-90.heic", 13, 4, 3, 1536, 2048),
        ("with-exif.heic", 13, 3, 4, 2048, 1536),
    ] {
        let info = heic_rs::probe(&load(name)).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert!(info.is_grid, "{name}");
        assert_eq!(info.primary_item, primary, "{name}");
        assert_eq!((info.width, info.height), (w, h), "{name}");
        let g = info
            .grid
            .unwrap_or_else(|| panic!("{name} has no grid info"));
        assert_eq!((g.rows, g.columns), (rows, cols), "{name}");
        // macOS tiles at 512 square above 512 pixels on a side.
        assert_eq!((g.tile_width, g.tile_height), (512, 512), "{name}");
        assert!(
            u64::from(g.rows * g.columns) * 512 * 512 >= u64::from(w) * u64::from(h),
            "{name}: the tiles must cover the output"
        );
    }
}

#[test]
fn the_dimg_reference_lists_tiles_in_order() {
    let bytes = load("photo-2048.heic");
    let ctx = Context::open(&bytes).expect("opens");
    let (grid, tiles) = ctx.grid(13).expect("resolves").expect("is a grid");
    assert_eq!(grid.rows, 3);
    assert_eq!(grid.columns, 4);
    assert_eq!(tiles, (1u32..=12).collect::<Vec<_>>());

    let bytes = load("checker-1024.heic");
    let ctx = Context::open(&bytes).expect("opens");
    let (_, tiles) = ctx.grid(5).expect("resolves").expect("is a grid");
    assert_eq!(tiles, vec![1, 2, 3, 4]);
}

#[test]
fn the_item_catalogue_matches_the_file() {
    let bytes = load("with-exif.heic");
    let ctx = Context::open(&bytes).expect("opens");
    assert_eq!(ctx.meta.items.len(), 15);
    for id in 1..=12u32 {
        let item = ctx.meta.item(id).unwrap_or_else(|| panic!("item {id}"));
        assert_eq!(item.item_type, *b"hvc1");
        // Tiles are marked hidden so that a viewer shows only the grid.
        assert!(item.hidden, "tile {id} should be hidden");
    }
    assert_eq!(ctx.meta.item(13).map(|i| i.item_type), Some(*b"grid"));
    assert_eq!(ctx.meta.item(14).map(|i| i.item_type), Some(*b"Exif"));
    assert_eq!(ctx.meta.item(15).map(|i| i.item_type), Some(*b"mime"));
    assert_eq!(
        ctx.meta.item(15).and_then(|i| i.content_type),
        Some("application/rdf+xml")
    );
}

#[test]
fn the_grid_item_is_read_out_of_idat() {
    // The `grid` payload uses iloc construction method 1, so reading it at all
    // proves the idat path works.
    let bytes = load("checker-1024.heic");
    let ctx = Context::open(&bytes).expect("opens");
    let loc = ctx.meta.location(5).expect("the grid item has a location");
    assert_eq!(loc.construction, heic_rs::meta::iloc::Construction::Idat);
    assert_eq!(loc.total_length(), Some(8));
    let data = ctx.item_data(5).expect("reads");
    assert_eq!(&data[..], &[0x00, 0x00, 0x01, 0x01, 0x04, 0x00, 0x04, 0x00]);
    // The tiles come from file offsets instead.
    assert_eq!(
        ctx.meta.location(1).map(|l| l.construction),
        Some(heic_rs::meta::iloc::Construction::File)
    );
}

#[test]
fn every_fixture_decodes_end_to_end() {
    // Container, codec and colour conversion, on every file in the corpus.
    // `tests/pixels.rs` checks that the samples are right; this only checks
    // that nothing in the chain refuses a file macOS itself wrote.
    for name in ALL {
        let image = heic_rs::decode(&load(name), &heic_rs::DecodeOptions::default())
            .unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(
            image.data.len(),
            image.row_bytes() * image.height as usize,
            "{name}"
        );
    }
}

#[test]
fn the_pixel_limit_refuses_a_large_file_before_decoding_it() {
    let options = heic_rs::DecodeOptions::default().with_max_pixels(Some(1000));
    let e = heic_rs::decode(&load("photo-2048.heic"), &options).expect_err("over the limit");
    assert_eq!(
        e,
        heic_rs::Error::PixelLimit {
            pixels: 2048 * 1536,
            max_pixels: 1000
        }
    );
}

#[test]
fn truncating_a_real_file_produces_an_error_not_a_panic() {
    let full = load("photo-2048.heic");
    for cut in [1usize, 8, 32, 100, 500, 800, 2000, 40_000] {
        let short = &full[..cut.min(full.len())];
        // Whatever comes back, it must come back.
        let _ = heic_rs::probe(short);
        let _ = heic_rs::decode(short, &heic_rs::DecodeOptions::default());
    }
}

#[test]
fn flipping_single_bytes_never_panics() {
    // A coarse smoke test over hostile input: walk the header region flipping
    // one byte at a time and require an error rather than a crash.
    let mut bytes = load("checker-1024.heic");
    for i in 0..600usize {
        let original = bytes[i];
        for patch in [0x00u8, 0xff, 0x7f] {
            bytes[i] = patch;
            let _ = heic_rs::probe(&bytes);
        }
        bytes[i] = original;
    }
}
